"""
Intermediate Representation (IR) for Bidirectional Programming.

This module implements a shared IR with get/put lens mechanisms to maintain
robust synchronization between semiformal specifications and Python code.

Key concepts:
- IR Node: Represents a program element (function, variable, expression, etc.)
- Lens: Bidirectional transformation with get (spec->code) and put (code->spec)
- Dependency Graph: Tracks data flow and dependencies
- Mapping: Maintains correspondence between spec and code nodes
- Incremental Updates: Merges changes without losing generated code
"""

import ast
from typing import Dict, List, Set, Optional, Any, Tuple, Union
from dataclasses import dataclass, field
from enum import Enum
import hashlib


class NodeType(Enum):
    """Types of IR nodes."""
    FUNCTION_DEF = "function_def"
    FUNCTION_CALL = "function_call"
    VARIABLE_ASSIGN = "variable_assign"
    VARIABLE_REF = "variable_ref"
    NL_EXPRESSION = "nl_expression"  # Natural language expression
    PSEUDOCODE = "pseudocode"  # Non-Python pseudocode
    STATEMENT = "statement"
    MODULE = "module"


class NodeStatus(Enum):
    """Status of an IR node."""
    INCOMPLETE = "incomplete"  # Needs generation
    GENERATED = "generated"    # Generated by LLM
    USER_EDITED = "user_edited"  # Modified by user (code side)
    SYNCED = "synced"          # In sync between spec and code
    NEEDS_REGEN = "needs_regen"  # Signature changed, needs regeneration


@dataclass
class SourceLocation:
    """Location in source code."""
    line: int
    col: int
    end_line: Optional[int] = None
    end_col: Optional[int] = None


@dataclass
class IRNode:
    """
    A node in the IR representing a program element.
    
    Each node can exist in both spec and code views, with potentially
    different representations. The lens mechanism manages the transformation.
    """
    id: str  # Unique identifier
    node_type: NodeType
    name: str  # Name of the element (function name, variable name, etc.)
    status: NodeStatus
    
    # Spec representation
    spec_location: Optional[SourceLocation] = None
    spec_ast: Optional[ast.AST] = None
    spec_text: str = ""
    spec_signature: str = ""  # Normalized signature for comparison
    spec_hash: str = ""  # Hash of spec content for change detection
    
    # Code representation
    code_location: Optional[SourceLocation] = None
    code_ast: Optional[ast.AST] = None
    code_text: str = ""
    code_signature: str = ""  # Normalized signature for comparison
    code_ast_path: str = ""  # Path to this node in code AST tree (e.g., "body[0].body[1]")
    
    # Dependencies
    depends_on: Set[str] = field(default_factory=set)  # IDs of nodes this depends on
    used_by: Set[str] = field(default_factory=set)     # IDs of nodes that use this
    
    # Metadata
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def is_incomplete(self) -> bool:
        """Check if this node needs generation."""
        return self.status in (NodeStatus.INCOMPLETE, NodeStatus.NEEDS_REGEN)
    
    def is_nl_expression(self) -> bool:
        """Check if this contains natural language."""
        return self.node_type == NodeType.NL_EXPRESSION or "..." in self.spec_text
    
    def has_generated_code(self) -> bool:
        """Check if this node has generated or user-edited code."""
        return self.status in (NodeStatus.GENERATED, NodeStatus.USER_EDITED) and bool(self.code_text)
    
    def compute_spec_hash(self) -> str:
        """Compute hash of spec content for change detection."""
        content = f"{self.spec_signature}:{self.spec_text}"
        return hashlib.md5(content.encode()).hexdigest()
    
    def signature_changed(self, new_signature: str) -> bool:
        """Check if the signature has changed."""
        return self.spec_signature != new_signature


@dataclass
class Lens:
    """
    Bidirectional transformation between spec and code representations.
    
    Implements the lens laws:
    - GetPut: put(s, get(s)) = s
    - PutGet: get(put(s, c)) = c
    - PutPut: put(put(s, c1), c2) = put(s, c2)
    """
    node_id: str
    
    def get(self, spec: str, context: 'ProgramIR') -> str:
        """Transform spec to code (spec -> code)."""
        raise NotImplementedError
    
    def put(self, code: str, spec: str, context: 'ProgramIR') -> str:
        """Transform code back to spec (code -> spec)."""
        raise NotImplementedError


class FunctionLens(Lens):
    """Lens for function definitions."""
    
    def get(self, spec: str, context: 'ProgramIR') -> str:
        """
        Generate code from spec function.
        
        If spec is incomplete (has ...), triggers LLM generation.
        If spec is complete, propagates with type annotations.
        """
        node = context.get_node(self.node_id)
        if not node:
            return spec
        
        if node.is_incomplete():
            # Mark for generation
            node.metadata['needs_generation'] = True
            return spec  # Will be handled by generator
        
        return spec
    
    def put(self, code: str, spec: str, context: 'ProgramIR') -> str:
        """
        Update spec from code changes.
        
        If code has implementation details, extract high-level intent.
        Preserve natural language constraints from spec.
        """
        node = context.get_node(self.node_id)
        if not node:
            return spec
        
        # Extract signature from code
        try:
            code_ast = ast.parse(code)
            if isinstance(code_ast.body[0], ast.FunctionDef):
                func_def = code_ast.body[0]
                
                # If spec is a stub, update signature but keep stub
                if "..." in spec:
                    args = [arg.arg for arg in func_def.args.args]
                    sig = f"def {func_def.name}({', '.join(args)}):"
                    return f"{sig}\n    ..."
                
                # Otherwise, reflect significant changes only
                return spec
        except:
            return spec


class VariableLens(Lens):
    """Lens for variable assignments."""
    
    def get(self, spec: str, context: 'ProgramIR') -> str:
        """Generate code from spec variable assignment."""
        node = context.get_node(self.node_id)
        if not node:
            return spec
        
        # Check if RHS is natural language
        if "=" in spec:
            var_name, rhs = spec.split("=", 1)
            rhs = rhs.strip()
            
            # If RHS is NL or ..., mark for generation
            if rhs == "..." or self._is_natural_language(rhs):
                node.metadata['needs_generation'] = True
                node.metadata['nl_description'] = rhs
        
        return spec
    
    def put(self, code: str, spec: str, context: 'ProgramIR') -> str:
        """Update spec from code variable assignment."""
        # If spec was NL, preserve it (don't replace with generated code)
        if "=" in spec:
            var_name, rhs = spec.split("=", 1)
            rhs = rhs.strip()
            if self._is_natural_language(rhs):
                return spec  # Keep NL in spec
        
        # Otherwise, update spec with code
        return code
    
    def _is_natural_language(self, text: str) -> bool:
        """Check if text is natural language."""
        # Simple heuristic: contains spaces and no Python operators
        has_spaces = " " in text
        no_parens = "(" not in text
        no_brackets = "[" not in text
        not_string = not text.startswith(("'", '"'))
        
        return has_spaces and no_parens and no_brackets and not_string and text != "..."


@dataclass
class ProgramIR:
    """
    Complete IR for a program, managing both spec and code views.
    
    This is the central data structure that maintains the bidirectional
    mapping and ensures consistency.
    """
    nodes: Dict[str, IRNode] = field(default_factory=dict)
    lenses: Dict[str, Lens] = field(default_factory=dict)
    spec_source: str = ""
    code_source: str = ""
    
    # Dependency graph (node_id -> set of dependencies)
    dependency_graph: Dict[str, Set[str]] = field(default_factory=dict)
    
    # Node lookup by name for faster merging
    _node_by_name: Dict[Tuple[NodeType, str], str] = field(default_factory=dict)
    
    def add_node(self, node: IRNode) -> None:
        """Add a node to the IR."""
        self.nodes[node.id] = node
        self._node_by_name[(node.node_type, node.name)] = node.id
        
        # Create appropriate lens
        if node.node_type == NodeType.FUNCTION_DEF:
            self.lenses[node.id] = FunctionLens(node.id)
        elif node.node_type == NodeType.VARIABLE_ASSIGN:
            self.lenses[node.id] = VariableLens(node.id)
    
    def get_node(self, node_id: str) -> Optional[IRNode]:
        """Get a node by ID."""
        return self.nodes.get(node_id)
    
    def get_node_by_name(self, node_type: NodeType, name: str) -> Optional[IRNode]:
        """Get a node by type and name."""
        node_id = self._node_by_name.get((node_type, name))
        return self.nodes.get(node_id) if node_id else None
    
    def get_incomplete_nodes(self) -> List[IRNode]:
        """Get all nodes that need generation."""
        return [n for n in self.nodes.values() if n.is_incomplete()]
    
    def add_dependency(self, node_id: str, depends_on_id: str) -> None:
        """Add a dependency relationship."""
        if node_id in self.nodes and depends_on_id in self.nodes:
            self.nodes[node_id].depends_on.add(depends_on_id)
            self.nodes[depends_on_id].used_by.add(node_id)
            
            if node_id not in self.dependency_graph:
                self.dependency_graph[node_id] = set()
            self.dependency_graph[node_id].add(depends_on_id)
    
    def merge_from_spec_update(self, new_ir: 'ProgramIR') -> Dict[str, str]:
        """
        Merge changes from a new spec parse into existing IR.
        
        This is the key method for bidirectional sync. It:
        1. Identifies which nodes are new, modified, or deleted
        2. Preserves generated code for existing nodes
        3. Updates signatures while keeping implementations
        4. Marks nodes for regeneration when needed
        
        Returns:
            Dict mapping node_id to change type ('added', 'modified', 'deleted', 'signature_changed')
        """
        changes = {}
        
        # Track existing nodes
        existing_nodes = set(self.nodes.keys())
        new_nodes = set(new_ir.nodes.keys())
        
        # Process each node in the new spec
        for new_node_id, new_node in new_ir.nodes.items():
            # Try to find matching existing node by name
            existing_node = self.get_node_by_name(new_node.node_type, new_node.name)
            
            if existing_node:
                # Node exists, check for changes
                change_type = self._merge_node(existing_node, new_node)
                if change_type:
                    changes[existing_node.id] = change_type
            else:
                # New node - add it
                self.add_node(new_node)
                changes[new_node.id] = 'added'
        
        # Identify deleted nodes (in old but not new)
        new_node_names = {(n.node_type, n.name) for n in new_ir.nodes.values()}
        for node_id, node in list(self.nodes.items()):
            if (node.node_type, node.name) not in new_node_names:
                # Node was removed from spec
                changes[node_id] = 'deleted'
                # Don't actually delete yet - might want to keep orphaned generated code
                node.metadata['deleted_from_spec'] = True
        
        # Update dependency graph
        self.dependency_graph = new_ir.dependency_graph.copy()
        
        # Update source
        self.spec_source = new_ir.spec_source
        
        return changes
    
    def _merge_node(self, existing: IRNode, new: IRNode) -> Optional[str]:
        """
        Merge a new node into an existing one.
        
        Returns the type of change, or None if no significant change.
        """
        # Check if signature changed
        if existing.spec_signature and new.spec_signature:
            if existing.signature_changed(new.spec_signature):
                return self._handle_signature_change(existing, new)
        
        # Check if content changed (beyond signature)
        old_hash = existing.spec_hash
        new.spec_hash = new.compute_spec_hash()
        
        if old_hash and old_hash != new.spec_hash:
            # Content changed
            return self._handle_content_change(existing, new)
        
        # Just update metadata and location
        existing.spec_location = new.spec_location
        existing.spec_ast = new.spec_ast
        existing.spec_text = new.spec_text
        existing.spec_signature = new.spec_signature
        existing.spec_hash = new.compute_spec_hash()
        
        return None
    
    def _handle_signature_change(self, existing: IRNode, new: IRNode) -> str:
        """
        Handle signature change in spec.
        
        Preserve generated code but mark for regeneration.
        """
        # Update spec side
        existing.spec_location = new.spec_location
        existing.spec_ast = new.spec_ast
        existing.spec_text = new.spec_text
        existing.spec_signature = new.spec_signature
        existing.spec_hash = new.compute_spec_hash()
        
        # If we have generated code, update its signature using AST manipulation
        if existing.has_generated_code() and existing.code_ast:
            updated_code_ast = self._update_code_signature(existing.code_ast, new.spec_ast, existing.node_type)
            if updated_code_ast:
                try:
                    existing.code_text = ast.unparse(updated_code_ast)
                    existing.code_ast = updated_code_ast
                    existing.code_signature = new.spec_signature
                except:
                    pass
        
        # Mark for regeneration since signature changed
        if existing.status == NodeStatus.GENERATED:
            existing.status = NodeStatus.NEEDS_REGEN
        
        return 'signature_changed'
    
    def _handle_content_change(self, existing: IRNode, new: IRNode) -> str:
        """Handle non-signature content change."""
        # Update spec
        existing.spec_location = new.spec_location
        existing.spec_ast = new.spec_ast
        existing.spec_text = new.spec_text
        existing.spec_hash = new.compute_spec_hash()
        
        # If we have generated code and it was from LLM, mark for regen
        if existing.status == NodeStatus.GENERATED:
            existing.status = NodeStatus.NEEDS_REGEN
        
        return 'modified'
    
    def _update_code_signature(self, code_ast: ast.AST, spec_ast: ast.AST, node_type: NodeType) -> Optional[ast.AST]:
        """
        Update the signature of generated code to match new spec signature.
        
        Uses AST manipulation to preserve implementation while updating signature.
        """
        if node_type == NodeType.FUNCTION_DEF:
            if isinstance(spec_ast, ast.FunctionDef):
                # Parse the code to get FunctionDef
                if isinstance(code_ast, ast.Module) and code_ast.body:
                    code_func = code_ast.body[0]
                    if isinstance(code_func, ast.FunctionDef):
                        # Update function signature from spec
                        code_func.name = spec_ast.name
                        code_func.args = spec_ast.args
                        code_func.returns = spec_ast.returns
                        code_func.decorator_list = spec_ast.decorator_list
                        return code_ast
                elif isinstance(code_ast, ast.FunctionDef):
                    code_ast.name = spec_ast.name
                    code_ast.args = spec_ast.args
                    code_ast.returns = spec_ast.returns
                    code_ast.decorator_list = spec_ast.decorator_list
                    return ast.Module(body=[code_ast], type_ignores=[])
        
        return None
    
    def get_dependencies(self, node_id: str) -> Set[str]:
        """Get all dependencies of a node."""
        return self.dependency_graph.get(node_id, set())
    
    def topological_sort(self) -> List[str]:
        """
        Return nodes in topological order (dependencies first).
        
        This is crucial for generation order - we need to generate
        dependencies before dependents.
        """
        # Kahn's algorithm
        in_degree = {nid: 0 for nid in self.nodes}
        
        for node_id, deps in self.dependency_graph.items():
            for dep in deps:
                if dep in in_degree:
                    in_degree[node_id] += 1
        
        queue = [nid for nid, degree in in_degree.items() if degree == 0]
        result = []
        
        while queue:
            node_id = queue.pop(0)
            result.append(node_id)
            
            # Reduce in-degree for nodes that depend on this one
            node = self.nodes[node_id]
            for dependent_id in node.used_by:
                if dependent_id in in_degree:
                    in_degree[dependent_id] -= 1
                    if in_degree[dependent_id] == 0:
                        queue.append(dependent_id)
        
        return result
    
    def apply_get(self) -> str:
        """
        Apply get transformation: spec -> code.
        
        Returns the generated code representation.
        """
        # Process nodes in topological order
        ordered_nodes = self.topological_sort()
        
        for node_id in ordered_nodes:
            node = self.nodes[node_id]
            lens = self.lenses.get(node_id)
            
            if lens:
                # Apply lens transformation
                node.code_text = lens.get(node.spec_text, self)
        
        return self._reconstruct_code()
    
    def apply_put(self, code_changes: Dict[str, str]) -> str:
        """
        Apply put transformation: code -> spec.
        
        Args:
            code_changes: Map of node_id to updated code text
        
        Returns the updated spec representation.
        """
        for node_id, new_code in code_changes.items():
            node = self.nodes.get(node_id)
            lens = self.lenses.get(node_id)
            
            if node and lens:
                # Apply reverse lens transformation
                node.spec_text = lens.put(new_code, node.spec_text, self)
                node.code_text = new_code
                node.status = NodeStatus.USER_EDITED
        
        return self._reconstruct_spec()
    
    def _reconstruct_code(self) -> str:
        """Reconstruct full code from nodes."""
        # Sort nodes by code location
        sorted_nodes = sorted(
            [n for n in self.nodes.values() if n.code_text],
            key=lambda n: n.code_location.line if n.code_location else float('inf')
        )
        
        lines = []
        for node in sorted_nodes:
            lines.append(node.code_text)
        
        return "\n".join(lines)
    
    def _reconstruct_spec(self) -> str:
        """Reconstruct full spec from nodes."""
        # Sort nodes by spec location
        sorted_nodes = sorted(
            [n for n in self.nodes.values() if n.spec_text],
            key=lambda n: n.spec_location.line if n.spec_location else float('inf')
        )
        
        lines = []
        for node in sorted_nodes:
            lines.append(node.spec_text)
        
        return "\n".join(lines)
    
    def to_dict(self) -> Dict[str, Any]:
        """Serialize IR to dictionary."""
        return {
            'nodes': {
                nid: {
                    'id': node.id,
                    'type': node.node_type.value,
                    'name': node.name,
                    'status': node.status.value,
                    'spec_text': node.spec_text,
                    'spec_signature': node.spec_signature,
                    'code_text': node.code_text,
                    'code_signature': node.code_signature,
                    'depends_on': list(node.depends_on),
                    'used_by': list(node.used_by),
                    'metadata': node.metadata
                }
                for nid, node in self.nodes.items()
            },
            'spec_source': self.spec_source,
            'code_source': self.code_source
        }
    
    def copy(self) -> 'ProgramIR':
        """Create a deep copy of this IR."""
        import copy
        return copy.deepcopy(self)


def create_node_id(node_type: NodeType, name: str, line: int) -> str:
    """Create a unique ID for a node."""
    return f"{node_type.value}:{name}:{line}"

